---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "weastur"
    assignees:
      - "weastur"
    labels:
      - "dependabot"
      - "needs triage"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "[deps-gh-actions] "
    schedule:
      interval: "weekly"
